<?php
/**
 * Sample configuration file.
 *
 * This file is shipped with the application as a reference. The real
 * config/config.php is generated by the browser-based installer the first
 * time the application is opened in a browser. Do NOT edit this file in
 * a production install — edit config/config.php instead.
 */

return [
    // Database connection (MySQL/MariaDB)
    'db' => [
        'driver'   => 'mysql',     // mysql | sqlite (sqlite is for tests only)
        'host'     => 'localhost',
        'port'     => 3306,
        'database' => 'porra',
        'username' => 'porra_user',
        'password' => '',
        'charset'  => 'utf8mb4',
        'prefix'   => 'pm_',
    ],

    // Site
    'site' => [
        'name'      => 'Porra Mundial 2026',
        'base_url'  => 'https://example.com',
        'timezone'  => 'Europe/Madrid',
        'locale'    => 'es',
    ],

    // Application key — 32 bytes, base64 encoded. Used for symmetric
    // encryption (TOTP secrets, SMTP password) and signed cookies.
    'app_key' => '',

    // Environment: 'production' (default), 'development'
    'env' => 'production',

    // Optional override for cookie params. The defaults are safe.
    'session' => [
        'name'     => 'porra_sess',
        'lifetime' => 0,            // 0 = until browser close
        'idle'     => 3600,         // seconds of inactivity before logout
    ],
];
