<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Read-only configuration loader. Supports dot-notation lookup.
 *
 * The configuration file is generated by the installer and lives at
 * config/config.php. When that file is missing the application is
 * considered "not installed" and the installer wizard is rendered.
 */
final class Config
{
    /** @var array<string, mixed> */
    private array $data = [];
    private bool $loaded = false;
    private string $file;

    public function __construct(string $file)
    {
        $this->file = $file;
    }

    public function file(): string
    {
        return $this->file;
    }

    public function exists(): bool
    {
        return is_file($this->file);
    }

    /** @return array<string, mixed> */
    public function all(): array
    {
        $this->load();
        return $this->data;
    }

    public function get(string $key, mixed $default = null): mixed
    {
        $this->load();
        $node = $this->data;
        foreach (explode('.', $key) as $part) {
            if (!is_array($node) || !array_key_exists($part, $node)) {
                return $default;
            }
            $node = $node[$part];
        }
        return $node;
    }

    private function load(): void
    {
        if ($this->loaded) {
            return;
        }
        $this->loaded = true;
        if (!is_file($this->file)) {
            $this->data = [];
            return;
        }
        /** @psalm-suppress UnresolvableInclude */
        $data = require $this->file;
        $this->data = is_array($data) ? $data : [];
    }
}
